Add /prometheus endpoint
Unleash/unleash-proxy pull request #78
Opened 2022-07-01 07:36 UTC by lordoflairs

Responding in a Prometheus exposition format
https://prometheus.io/docs/instrumenting/exposition_formats/

## About the changes

To be able to monitor if the unleash-proxy is up and running from Prometheus we need an endpoint that we can scrape i.e. responds in a format conforming to Prometheus exposition format.

Closes # .

### Important files

## Discussion points

This simple solution will suffice for us. Hopefully it can be built on further if you want more metrics.
I did not expose any other internal metrics. Did not know your policy on that or if you would like to use any other library for that in that case.

2022-07-04 07:13 UTC, sighphyre requested changes
This looks good, thanks so much!

I have a small request: on Unleash server, the promethus metrics are bound to `/internal-backstage/prometheus`, I think we should do the same here for consistencies sake. Would it be possible to update this to have the same path? (Alternatively, feel free to tell me that's a terrible idea!)

2022-07-05 10:32 UTC, sighphyre approved these changes
LGTM!

2022-07-05 11:59 UTC, merged

2022-07-05 12:00 UTC, sighphyre commented
@lordoflairs Thanks for much for this and for doing running with the suggested patch. Merged!

2022-07-18 06:14 UTC, Meemaw commented
Is it possible to disable this, like one the server? This can potentially expose sensitive underlying host information.