WIP: add httpOptions (just need sage advice from the code owner)
Unleash/unleash-proxy pull request #81
Opened 2022-07-14 17:37 UTC by CaptainGlac1er

## About the changes

Should allow adding in a httpagent if gitlab is using self signed cert. I think I made this not be a breaking change just need a little bit help to make this a successful improvement. 😊

Closes # .

### Important files

## Discussion points

2022-07-18 11:34 UTC, thomasheartman requested changes
Sounds like a good use case and the changes look sensible to me 🙌🏼  Thank you so much for putting in the effort! I've added some minor change suggestions for the test descriptions, but that's it from my side. However, I'll need an extra set of eyes to confirm that this is all good otherwise.

Thanks again!

2022-07-18 11:34 UTC, thomasheartman commented on src/test/config.test.ts
> +test('when not passed with httpOptions the config should not contain that property', () => {
Minor test description rewording suggestion 😄 

```suggestion
test('should not set config.httpOptions if no http options are provided at creation', () => {
```

2022-07-18 11:34 UTC, thomasheartman commented on src/test/config.test.ts
> +test('when passed with agent in httpOptions config.httpOptions.agent should be callable with url', () => {
```suggestion
test('should load the passed-in http agent when config.httpOptions is provided', () => {
```

2022-07-18 12:12 UTC, thomasheartman approved these changes
Nice one! Thanks for the quick fixup 😄 That's all from my end. I'm still waiting for someone more familiar with the proxy to give it a go-ahead, but should be fine, I reckon 🥳

2022-07-18 12:16 UTC, CaptainGlac1er commented
@thomasheartman sweet thanks!

2022-07-21 11:24 UTC, sighphyre approved these changes
Thanks! This looks good to me

2022-07-21 11:24 UTC, merged